stages:
  # Ingestion step: Just verify that the data is there
  ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/raw/train.csv
      - data/raw/test.csv
  
  # Preprocessing step: Take raw data and generate the processed one.
  preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv

  # Train step: Take processed data and register it in MLflow.
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train_processed.csv